# Generated by Django 5.2.3 on 2025-01-27 12:00

import django.db.models.deletion
import stl_uploads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stl_file', models.FileField(upload_to=stl_uploads.models.stl_upload_path)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed'), ('ready', 'Ready for Print')], default='uploaded', max_length=20)),
                ('processing_log', models.TextField(blank=True)),
                ('print_quality', models.CharField(choices=[('draft', 'Draft (0.3mm)'), ('normal', 'Normal (0.2mm)'), ('fine', 'Fine (0.15mm)'), ('ultra_fine', 'Ultra Fine (0.1mm)')], default='normal', max_length=20)),
                ('infill_percentage', models.CharField(choices=[('10', '10%'), ('15', '15%'), ('20', '20%'), ('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], default='20', max_length=3)),
                ('supports_needed', models.BooleanField(default=False)),
                ('estimated_print_time', models.CharField(blank=True, max_length=50)),
                ('estimated_material_usage', models.FloatField(blank=True, help_text='Material usage in grams', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='stl_previews/')),
                ('gcode_file', models.FileField(blank=True, null=True, upload_to='gcode_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_for_printing', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'Printing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('stl_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to='stl_uploads.stlfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]